import preset

PRESET = preset.EMPTY_3D
TITLE = "Gravity Simulator"
SIZE = 1000
BACKGROUND = "white"
G = 0.1
MASS_MIN = 1
MASS_MAX = 4e4
VELOCITY_MAX = 10
MAX_PATHS = 1000
CAMERA_COORD_STEP = 5
CAMERA_ANGLE_STEP = 1
CAMERA_ACCELERATION = 1.1
